definitions:
  deck.Card:
    properties:
      code:
        type: string
      rank:
        $ref: '#/definitions/deck.Rank'
      suit:
        $ref: '#/definitions/deck.Suit'
    type: object
  deck.Rank:
    enum:
    - ACE
    - "2"
    - "3"
    - "4"
    - "5"
    - "6"
    - "7"
    - "8"
    - "9"
    - "10"
    - JOKER
    - QUEEN
    - KING
    type: string
    x-enum-varnames:
    - Ace
    - Two
    - Three
    - Four
    - Five
    - Six
    - Seven
    - Eight
    - Nine
    - Ten
    - Jack
    - Queen
    - King
  deck.Suit:
    enum:
    - SPADES
    - DIAMONDS
    - CLUBS
    - HEARTS
    type: string
    x-enum-varnames:
    - Spades
    - Diamonds
    - Clubs
    - Hearts
  responses.DrawDeckResponse:
    properties:
      cards:
        description: |-
          List of cards drawn from the deck
          example: [{ "rank": "ACE", "suit": "SPADES", "code": "AS" }]
        items:
          $ref: '#/definitions/deck.Card'
        type: array
    type: object
  responses.ErrorResponse:
    properties:
      message:
        description: |-
          List of cards drawn from the deck
          example: "something went wrong"
        type: string
    type: object
  responses.NewDeckResponse:
    properties:
      deck_id:
        description: |-
          Deck ID
          example: 1674b1fa-f1d5-4453-b617-88c84b6df7ea
        type: string
      remaining:
        description: |-
          Number of cards remaining in the deck
          example: 52
        type: integer
      shuffled:
        description: |-
          Whether the deck was shuffled or not
          example: false
        type: boolean
    type: object
  responses.OpenDeckResponse:
    properties:
      cards:
        description: |-
          List of cards in the deck
          example: [{ "rank": "ACE", "suit": "SPADES", "code": "AS" }]
        items:
          $ref: '#/definitions/deck.Card'
        type: array
      deck_id:
        description: |-
          Deck ID
          example: 1674b1fa-f1d5-4453-b617-88c84b6df7ea
        type: string
      remaining:
        description: |-
          Number of cards remaining in the deck
          example: 52
        type: integer
      shuffled:
        description: |-
          Whether the deck was shuffled or not
          example: false
        type: boolean
    type: object
info:
  contact: {}
paths:
  /deck:
    get:
      consumes:
      - application/json
      description: Returns a new deck of cards with optional shuffle and cards parameter
      parameters:
      - description: Shuffle the deck
        in: query
        name: shuffle
        type: boolean
      - description: Specific card codes
        in: query
        name: cards
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responses.NewDeckResponse'
      summary: Get a new deck of cards
  /deck/draw/{id}:
    get:
      consumes:
      - application/json
      description: Returns a deck of cards drawn
      parameters:
      - description: Deck ID
        in: path
        name: id
        required: true
        type: string
      - description: Number of cards you want to draw from the deck
        in: query
        name: count
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responses.DrawDeckResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/responses.ErrorResponse'
      summary: Draw cards from the deck
  /deck/open/{id}:
    get:
      consumes:
      - application/json
      description: Returns a deck of cards
      parameters:
      - description: Deck ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responses.OpenDeckResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/responses.ErrorResponse'
      summary: Open a deck of cards
swagger: "2.0"
